services:
  - type: web
    name: chaty-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host=0.0.0.0 --port=10000
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: GROQ_API_KEY
        sync: false 
